## Python NumPy

### Characteristics of python numpy


*   array processing package
*   provides multidimensional array object that stores elements of same data type
*   number of dimensions in an array = rank (row)
*   size of the array along each dimension = shape (column)




In [ ]:
import numpy as np

array1 = np.array([1,2,3,4,5]) # from list
print(array1)

array2 = np.array((1,2,3,4,5)) # from tuple
print(array2)

array3 = np.array([[1,2,3],[4,5,6]]) # 2D array
print(array3)

[1 2 3 4 5]
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
array3.shape

(2, 3)

In [ ]:
array3.size

6

In [ ]:
# numpy array behavior when array contains characters
array4 = np.array(['a','b'])
array4

array(['a', 'b'], dtype='<U1')

In [ ]:
array5 = array1[2]
array5

np.int64(3)

In [ ]:
import numpy as np

array6 = np.array([
    [-1, 2, 0, 4],
    [4, -0.5, 6, 0],
    [2.6, 0, 7, 8],
    [3, -7, 4, 2.0]
])

print(array6)

# slicing
array7 = array6[::2, :3] # row wise and column wise
print(array7)

# access specific element
array8 = array6[1,2]
print(array8)

# access specific elements
array9 = array6[[1,1,2,3], [3,2,3,0]]
print(array9)

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
[[-1.   2.   0. ]
 [ 2.6  0.   7. ]]
6.0
[0. 6. 8. 3.]


In [ ]:
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[4, 3],
              [2, 1]])

print("Adding 1 to every element:\n", a + 1)
print("Subtracting 2 from each element:\n", b - 2)
print("Sum of all array elements:", a.sum())
print("Array sum:\n", a + b)

Adding 1 to every element:
 [[2 3]
 [4 5]]
Subtracting 2 from each element:
 [[ 2  1]
 [ 0 -1]]
Sum of all array elements: 10
Array sum:
 [[5 5]
 [5 5]]


In [ ]:
array10 = np.array([1,3,4], dtype=np.int32)
array10
print(array10.dtype)

int32


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.sqrt(a))
print(a.T)

[[5 5]
 [5 5]]
[[-3 -1]
 [ 1  3]]
[[4 6]
 [6 4]]
[[0.25       0.66666667]
 [1.5        4.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1 3]
 [2 4]]


## Pandas